In [1]:
import pandas as pd
df=pd.read_csv("messy_data.csv")
print(df)

   Customer_ID   Age   Income Product_Category  Quantity     Sales  Discount  \
0         C001  22.0  24000.0      Electronics       2.0   42000.0       5.0
1         C002  25.0  28000.0         Clothing       3.0   15000.0       8.0
2         C003  29.0 -35000.0        Furniture       1.0   28000.0      10.0
3         C004  32.0  42000.0      Electronics       4.0   68000.0       7.0
4         C005  35.0  48000.0          Grocery       6.0   18000.0       3.0
5         C006  38.0 -52000.0         Clothing       5.0   24000.0       6.0
6         C007  41.0 -58000.0        Furniture       2.0   52000.0      12.0
7         C008  45.0  65000.0      Electronics       3.0   75000.0       8.0
8         C009  48.0  72000.0          Grocery       8.0   26000.0       4.0
9         C010  52.0  80000.0        Furniture       4.0   85000.0      15.0
10        C011  27.0  31000.0         Clothing       2.0   11000.0       5.0
11        C012  31.0  39000.0      Electronics       3.0   55000.0       6.0
12        C013  36.0  47000.0          Grocery       7.0   21000.0       3.0
13        C014  40.0  55000.0              NaN       2.0   46000.0      10.0
14        C015  44.0  63000.0      Electronics       5.0   92000.0       9.0
15        C016  50.0  76000.0         Clothing       4.0   30000.0      12.0
16        C017  55.0  88000.0        Furniture       3.0   72000.0      14.0
17        C018  24.0  26000.0          Grocery       NaN   19000.0       2.0
18        C019  28.0  33000.0      Electronics       2.0   38000.0       5.0
19        C019  28.0  33000.0      Electronics       2.0   38000.0       5.0
20        C020  34.0  45000.0         Clothing       NaN   27000.0       7.0
21        C021   NaN  54000.0        Furniture       NaN   58000.0      11.0
22        C022  43.0      NaN      Electronics       4.0       8.0       8.0
23        C023  47.0  69000.0          Grocery       5.0   23000.0       4.0
24        C024  53.0  85000.0        Furniture       2.0   61000.0      13.0
25        C025  58.0  95000.0      Electronics       6.0  115000.0       1.0
26        C030   NaN  59000.0         Clothing       5.0   28000.0       NaN
27        C030  42.0  59000.0         Clothing       5.0   28000.0       NaN
28        C026  23.0  25000.0         Clothing       3.0   14000.0       NaN
29        C027  30.0  37000.0          Grocery       7.0   17000.0       NaN
30        C028   NaN  43000.0      Electronics       2.0   47000.0       NaN
31        C029   NaN  50000.0        Furniture       4.0   65000.0       NaN
32        C030  42.0  59000.0         Clothing       5.0   28000.0       NaN
33        C031  46.0  67000.0      Electronics       3.0   78000.0       7.0
34        C032   NaN  79000.0        Furniture       4.0   88000.0      12.0
35        C033   NaN  91000.0          Grocery       8.0   31000.0       5.0
36        C034  26.0  30000.0         Clothing       6.0   21000.0       7.0
37        C035  32.0  41000.0      Electronics       3.0   59000.0       6.0
38        C036  38.0  53000.0        Furniture       2.0   48000.0      10.0
39        C037  45.0  64000.0          Grocery       9.0   29000.0       4.0
40        C038  49.0  74000.0      Electronics       5.0   98000.0       9.0
41        C039  54.0  87000.0        Furniture       3.0   76000.0      13.0
42        C040  59.0  98000.0         Clothing       4.0   35000.0      11.0
43        C041  21.0  23000.0          Grocery       5.0       NaN       2.0
44        C042   NaN  36000.0      Electronics       4.0   61000.0       6.0
45        C043  35.0  46000.0        Furniture       2.0   43000.0       9.0
46        C044   NaN  57000.0         Clothing       7.0   33000.0       8.0
47        C045  47.0  70000.0      Electronics       6.0  108000.0      10.0
48        C046  52.0  82000.0          Grocery      10.0   36000.0       5.0
49        C047  57.0  93000.0        Furniture       5.0  105000.0      14.0
50        C048  27.0  32000.0         Clothing       4.0   19000.0       6.0
51        C049  36.0  49000.0      Electronics       3.0   64000.0       7.0
52        C050  43.0  60000.0        Furniture       4.0   70000.0      11.0

    Profit
0     6200
1     2800
2     4200
3    10500
4     3500
5     4200
6     7800
7    12500
8     5200
9    12800
10    2100
11    8500
12    4100
13    6900
14   14500
15    5200
16   10500
17    3800
18    5800
19    5800
20    4800
21    8500
22   12800
23    4600
24    9200
25   18500
26    5100
27    5100
28    2600
29    3300
30    7200
31    9800
32    5100
33   12000
34   13200
35    6200
36    3900
37    9000
38    7200
39    5700
40   15200
41   11200
42    6100
43    2300
44    9400
45    6500
46    5900
47   17000
48    7200
49   15600
50    3500
51    9800
52   10400

In [2]:
#Data Type Checking
df.dtypes

Customer_ID          object
Age                 float64
Income              float64
Product_Category     object
Quantity            float64
Sales               float64
Discount            float64
Profit                int64
dtype: object

Missing-Value Analysis

In [3]:
# Count the total missing values
print(df.isnull().sum())

#Check whether missing values exist
print("\nmissing values exist: ",df.isnull().any())


#only show the missing value
missing = df.isnull().sum()
missing[missing > 0]

Customer_ID         0
Age                 8
Income              1
Product_Category    1
Quantity            3
Sales               1
Discount            7
Profit              0
dtype: int64

missing values exist:  Customer_ID         False
Age                  True
Income               True
Product_Category     True
Quantity             True
Sales                True
Discount             True
Profit              False
dtype: bool

Age                 8
Income              1
Product_Category    1
Quantity            3
Sales               1
Discount            7
dtype: int64

Duplicate Analysis

In [4]:
#Check total duplicate rows
print(df.duplicated().sum())

#Display duplicate rows
print(df[df.duplicated()])

#Remove duplicate rows
print( df.drop_duplicates())

2
   Customer_ID   Age   Income Product_Category  Quantity    Sales  Discount  \
19        C019  28.0  33000.0      Electronics       2.0  38000.0       5.0
32        C030  42.0  59000.0         Clothing       5.0  28000.0       NaN

    Profit
19    5800
32    5100
   Customer_ID   Age   Income Product_Category  Quantity     Sales  Discount  \
0         C001  22.0  24000.0      Electronics       2.0   42000.0       5.0
1         C002  25.0  28000.0         Clothing       3.0   15000.0       8.0
2         C003  29.0 -35000.0        Furniture       1.0   28000.0      10.0
3         C004  32.0  42000.0      Electronics       4.0   68000.0       7.0
4         C005  35.0  48000.0          Grocery       6.0   18000.0       3.0
5         C006  38.0 -52000.0         Clothing       5.0   24000.0       6.0
6         C007  41.0 -58000.0        Furniture       2.0   52000.0      12.0
7         C008  45.0  65000.0      Electronics       3.0   75000.0       8.0
8         C009  48.0  72000.0          Grocery       8.0   26000.0       4.0
9         C010  52.0  80000.0        Furniture       4.0   85000.0      15.0
10        C011  27.0  31000.0         Clothing       2.0   11000.0       5.0
11        C012  31.0  39000.0      Electronics       3.0   55000.0       6.0
12        C013  36.0  47000.0          Grocery       7.0   21000.0       3.0
13        C014  40.0  55000.0              NaN       2.0   46000.0      10.0
14        C015  44.0  63000.0      Electronics       5.0   92000.0       9.0
15        C016  50.0  76000.0         Clothing       4.0   30000.0      12.0
16        C017  55.0  88000.0        Furniture       3.0   72000.0      14.0
17        C018  24.0  26000.0          Grocery       NaN   19000.0       2.0
18        C019  28.0  33000.0      Electronics       2.0   38000.0       5.0
20        C020  34.0  45000.0         Clothing       NaN   27000.0       7.0
21        C021   NaN  54000.0        Furniture       NaN   58000.0      11.0
22        C022  43.0      NaN      Electronics       4.0       8.0       8.0
23        C023  47.0  69000.0          Grocery       5.0   23000.0       4.0
24        C024  53.0  85000.0        Furniture       2.0   61000.0      13.0
25        C025  58.0  95000.0      Electronics       6.0  115000.0       1.0
26        C030   NaN  59000.0         Clothing       5.0   28000.0       NaN
27        C030  42.0  59000.0         Clothing       5.0   28000.0       NaN
28        C026  23.0  25000.0         Clothing       3.0   14000.0       NaN
29        C027  30.0  37000.0          Grocery       7.0   17000.0       NaN
30        C028   NaN  43000.0      Electronics       2.0   47000.0       NaN
31        C029   NaN  50000.0        Furniture       4.0   65000.0       NaN
33        C031  46.0  67000.0      Electronics       3.0   78000.0       7.0
34        C032   NaN  79000.0        Furniture       4.0   88000.0      12.0
35        C033   NaN  91000.0          Grocery       8.0   31000.0       5.0
36        C034  26.0  30000.0         Clothing       6.0   21000.0       7.0
37        C035  32.0  41000.0      Electronics       3.0   59000.0       6.0
38        C036  38.0  53000.0        Furniture       2.0   48000.0      10.0
39        C037  45.0  64000.0          Grocery       9.0   29000.0       4.0
40        C038  49.0  74000.0      Electronics       5.0   98000.0       9.0
41        C039  54.0  87000.0        Furniture       3.0   76000.0      13.0
42        C040  59.0  98000.0         Clothing       4.0   35000.0      11.0
43        C041  21.0  23000.0          Grocery       5.0       NaN       2.0
44        C042   NaN  36000.0      Electronics       4.0   61000.0       6.0
45        C043  35.0  46000.0        Furniture       2.0   43000.0       9.0
46        C044   NaN  57000.0         Clothing       7.0   33000.0       8.0
47        C045  47.0  70000.0      Electronics       6.0  108000.0      10.0
48        C046  52.0  82000.0          Grocery      10.0   36000.0       5.0
49        C047  57.0  93000.0        Furniture       5.0  105000.0      14.0
50        C048  27.0  32000.0         Clothing       4.0   19000.0       6.0
51        C049  36.0  49000.0      Electronics       3.0   64000.0       7.0
52        C050  43.0  60000.0        Furniture       4.0   70000.0      11.0

    Profit
0     6200
1     2800
2     4200
3    10500
4     3500
5     4200
6     7800
7    12500
8     5200
9    12800
10    2100
11    8500
12    4100
13    6900
14   14500
15    5200
16   10500
17    3800
18    5800
20    4800
21    8500
22   12800
23    4600
24    9200
25   18500
26    5100
27    5100
28    2600
29    3300
30    7200
31    9800
33   12000
34   13200
35    6200
36    3900
37    9000
38    7200
39    5700
40   15200
41   11200
42    6100
43    2300
44    9400
45    6500
46    5900
47   17000
48    7200
49   15600
50    3500
51    9800
52   10400

In [5]:
#Display duplicate rows
print(df[df.duplicated()])

   Customer_ID   Age   Income Product_Category  Quantity    Sales  Discount  \
19        C019  28.0  33000.0      Electronics       2.0  38000.0       5.0
32        C030  42.0  59000.0         Clothing       5.0  28000.0       NaN

    Profit
19    5800
32    5100

Unique-Value Analysis

In [6]:
#Find unique values in a column
print(df['Product_Category'].unique())

#Count unique values
print(df['Product_Category'].nunique())

#Find unique values for all columns
print(df.nunique()) #This shows how many unique values each column contains.

#Display frequency of each unique value
print(df['Product_Category'].value_counts())

['Electronics' 'Clothing' 'Furniture' 'Grocery' nan]
4
Customer_ID         50
Age                 34
Income              49
Product_Category     4
Quantity            10
Sales               45
Discount            15
Profit              40
dtype: int64
Product_Category
Electronics    16
Clothing       13
Furniture      13
Grocery        10
Name: count, dtype: int64

Invalid-Value Detection

In [7]:
#Age
print(df[(df['Age'] < 18) | (df['Age'] > 100)])

Empty DataFrame
Columns: [Customer_ID, Age, Income, Product_Category, Quantity, Sales, Discount, Profit]
Index: []

In [8]:
#Income
df[df['Income'] < 0]

,Customer_ID,Age,Income,Product_Category,Quantity,Sales,Discount,Profit
2,C003,29.0,-35000.0,Furniture,1.0,28000.0,10.0,4200
5,C006,38.0,-52000.0,Clothing,5.0,24000.0,6.0,4200
6,C007,41.0,-58000.0,Furniture,2.0,52000.0,12.0,7800

In [9]:
#Quantity
df[df['Quantity'] <= 0]

#Sales
df[df['Sales'] < 0]

#Discount
df[(df['Discount'] < 0) | (df['Discount'] > 100)]

#Profit
df[df['Profit'] < 0]

#Product Category
df[~df['Product_Category'].isin(
    ['Electronics', 'Clothing', 'Furniture', 'Grocery']
)]

,Customer_ID,Age,Income,Product_Category,Quantity,Sales,Discount,Profit
13,C014,40.0,55000.0,NaN,2.0,46000.0,10.0,6900

Groupby Analysis

In [10]:
#Product Category — Total Sales
group_analysis = df.groupby("Product_Category")["Sales"].sum()
print(group_analysis)

Product_Category
Clothing        313000.0
Electronics    1038008.0
Furniture       851000.0
Grocery         220000.0
Name: Sales, dtype: float64

In [11]:
#Product Category — Average Sales
group_analysis = df.groupby("Product_Category")["Sales"].mean()
print(group_analysis)

Product_Category
Clothing       24076.923077
Electronics    64875.500000
Furniture      65461.538462
Grocery        24444.444444
Name: Sales, dtype: float64

In [12]:
#Product Category — Multiple Analysis
group_analysis = df.groupby("Product_Category").agg({
    "Sales": "sum",
    "Profit": "sum",
    "Quantity": "sum"
})

print(group_analysis)

                      Sales  Profit  Quantity
Product_Category
Clothing           313000.0   56400      53.0
Electronics       1038008.0  174700      57.0
Furniture          851000.0  126900      36.0
Grocery            220000.0   45900      65.0

In [13]:
import pandas as pd

data = {
    "Amount": ["50000", "60000", "75000"],
    "Date": ["25-09-2026", "26-09-2026", "27-09-2026"]
}

df = pd.DataFrame(data)

# String → Numeric
df["Amount"] = pd.to_numeric(df["Amount"])

# String → Date
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

print(df)
print(df.dtypes)

   Amount       Date
0   50000 2026-09-25
1   60000 2026-09-26
2   75000 2026-09-27
Amount             int64
Date      datetime64[ns]
dtype: object